import { products,type Product,type ProductVariant } from '../data/products'
export function getDefaultVariant(product:Product){return product.variants?.find(v=>(v.active??true)&&v.stock>0)??product.variants?.find(v=>v.active??true)??product.variants?.[0]}
export function getVariant(product:Product,variantId?:string){return variantId?product.variants?.find(v=>v.id===variantId)??getDefaultVariant(product):getDefaultVariant(product)}
export function getProductDisplayPrice(product:Product){const active=product.variants?.filter(v=>v.active??true)??[];return active.length?Math.min(...active.map(v=>v.retailPrice)):product.retailPrice}
export function getProductDisplayCompareAtPrice(product:Product){const values=(product.variants??[]).map(v=>v.compareAtPrice).filter((v):v is number=>typeof v==='number');return values.length?Math.max(...values):product.compareAtPrice}
export function getProductPrice(product:Product,variantId?:string){return getVariant(product,variantId)?.retailPrice??product.retailPrice}
export function getProductCompareAtPrice(product:Product,variantId?:string){return getVariant(product,variantId)?.compareAtPrice??product.compareAtPrice}
export function getProductStock(product:Product,variantId?:string){if(!product.variants?.length)return product.stock;if(variantId)return Math.max(0,(getVariant(product,variantId)?.stock??0)-(getVariant(product,variantId)?.safetyStock??0));return product.variants.filter(v=>v.active??true).reduce((sum,v)=>sum+Math.max(0,v.stock-(v.safetyStock??0)),0)}
export function getProductArt(product:Product,variantId?:string){return getVariant(product,variantId)?.art??product.art}
export function getVariantLabel(product:Product,variantId?:string){const v=getVariant(product,variantId);if(!v)return'';return Object.entries(v.attributes).map(([key,value])=>product.options?.find(o=>o.name===key)?.values.find(x=>x.value===value)?.label??value).join(' · ')}
export function findMatchingVariant(product:Product,selection:Record<string,string>){return product.variants?.find(v=>(v.active??true)&&Object.entries(selection).every(([key,value])=>v.attributes[key]===value))}
export function getAvailableOptionValues(product:Product,optionName:string,selection:Record<string,string>){const option=product.options?.find(o=>o.name===optionName);return(option?.values??[]).map(value=>{const next={...selection,[optionName]:value.value};const available=product.variants?.some(v=>(v.active??true)&&v.stock>0&&Object.entries(next).every(([k,val])=>v.attributes[k]===val))??true;return{...value,available}})}
export function getUpsellProducts(product:Product,source=products){return(product.upsellIds??[]).map(id=>source.find(p=>p.id===id)).filter((p):p is Product=>Boolean(p))}
export function getCrossSellProducts(product:Product,source=products){const explicit=(product.crossSellIds??[]).map(id=>source.find(p=>p.id===id)).filter((p):p is Product=>Boolean(p));if(explicit.length)return explicit;return source.filter(p=>p.id!==product.id&&p.tags.some(tag=>product.tags.includes(tag))).slice(0,4)}
export function getCartCrossSellProducts(productIds:string[],source=products){const set=new Set<string>();for(const id of productIds){const p=source.find(x=>x.id===id);if(!p)continue;for(const c of getCrossSellProducts(p,source))if(!productIds.includes(c.id))set.add(c.id)}return[...set].map(id=>source.find(p=>p.id===id)).filter((p):p is Product=>Boolean(p)).slice(0,4)}
export type{ProductVariant}
