import type{ReactNode} from 'react'
import {HeadContent,Outlet,Scripts,createRootRoute,useRouterState} from '@tanstack/react-router'
import {ShopProvider} from '../lib/shop'
import {Layout} from '../components/Layout'
import {ConsentBanner} from '../components/ConsentBanner'
import {getStorefrontShell} from '../server/storefront'
import appCss from '../styles/app.css?url'
export const Route=createRootRoute({loader:()=>getStorefrontShell(),head:()=>({meta:[{charSet:'utf-8'},{name:'viewport',content:'width=device-width, initial-scale=1'},{title:'DinoToys.hu – játékok, ajándékötletek és trendtermékek'},{name:'description',content:'Modern magyar játékwebshop variánsokkal, ajándékkeresővel, gyors kosárral és átlátható vásárlási információkkal.'},{name:'robots',content:'index,follow,max-image-preview:large'},{property:'og:locale',content:'hu_HU'},{property:'og:type',content:'website'},{property:'og:site_name',content:'DinoToys.hu'},{property:'og:title',content:'DinoToys.hu – játékok, ajándékötletek és trendtermékek'},{property:'og:description',content:'Modern játékwebshop variánsokkal, okos ajánlatokkal és ajándékkereséssel.'},{name:'twitter:card',content:'summary_large_image'},{name:'theme-color',content:'#ffffff'}],links:[{rel:'stylesheet',href:appCss},{rel:'icon',href:'/favicon.svg',type:'image/svg+xml'},{rel:'manifest',href:'/manifest.webmanifest'},{rel:'preconnect',href:'https://fonts.googleapis.com'},{rel:'preconnect',href:'https://fonts.gstatic.com',crossOrigin:'anonymous'},{rel:'stylesheet',href:'https://fonts.googleapis.com/css2?family=Manrope:wght@500;600;700;800&family=Inter:wght@400;500;600;700&display=swap'}]}),component:Root})
function Root(){const isAdmin=useRouterState({select:s=>s.location.pathname.startsWith('/admin')}),shell=Route.useLoaderData(),threshold=Number(shell?.settings?.['shop.free_shipping_threshold_huf']??15000);return <Document><ShopProvider freeShippingThreshold={threshold} promotions={shell?shell.promotions:undefined}>{isAdmin?<Outlet/>:<><Layout shell={shell}><Outlet/></Layout><ConsentBanner/></>}</ShopProvider></Document>}
function Document({children}:{children:ReactNode}){return <html lang="hu"><head><HeadContent/></head><body>{children}<Scripts/></body></html>}
