import {createFileRoute,Link} from '@tanstack/react-router'
import {useState} from 'react'
import {money} from '../lib/format'
import {useShop} from '../lib/shop'
import {getProductArt,getProductPrice,getVariantLabel} from '../lib/catalog'
export const Route=createFileRoute('/checkout')({head:()=>({meta:[{title:'Pénztár | DinoToys.hu'},{name:'robots',content:'noindex,nofollow'}]}),component:Checkout})
function Checkout(){const shop=useShop(),[done,setDone]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[result,setResult]=useState<any>(null);if(done)return <div className="container section"><div className="success-card"><span>✓</span><h1>{result?.order_number?`Rendelés #${result.order_number} létrehozva`:'Demo rendelés rögzítve'}</h1><p>{result?.order_number?`A szerver variánsszinten újraárazta és lefoglalta a készletet. Fizetendő: ${money(result.total_huf)}.`:'Demo módban nem kerül adatbázisba.'}</p><Link to="/" className="btn btn-primary">Főoldal</Link></div></div>;
 return <div className="container section checkout-page">{error&&<div className="admin2-error">{error}</div>}<div className="page-title"><span className="eyebrow">Gyors pénztár</span><h1>Checkout</h1><p>A rendelés véglegesítése előtt látod a teljes fizetendő összeget és a kapcsolódó feltételeket.</p></div><div className="checkout-grid"><form className="checkout-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError(null);try{const form=new FormData(e.currentTarget),live=shop.cart.every(line=>/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(line.productId));if(!live){setDone(true);return}const response=await fetch('/api/v1/checkout',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({idempotencyKey:crypto.randomUUID(),email:String(form.get('email')||''),phone:String(form.get('phone')||''),couponCode:shop.appliedCoupon?.code??null,shippingAddress:{name:String(form.get('name')||''),countryCode:'HU',postalCode:String(form.get('postalCode')||''),city:String(form.get('city')||''),line1:String(form.get('line1')||'')},items:shop.cart.map(line=>({productId:line.productId,variantId:line.variantId,quantity:line.quantity}))})});const payload=await response.json() as any;if(!response.ok||payload?.ok===false)throw new Error(payload?.error?.message||'A rendelés létrehozása sikertelen.');setResult(payload.data);setDone(true)}catch(err){setError(err instanceof Error?err.message:'Checkout hiba')}finally{setBusy(false)}}}><section><h2>1. Kapcsolat</h2><div className="form-grid"><label><span>E-mail</span><input name="email" type="email" autoComplete="email" required/></label><label><span>Telefon</span><input name="phone" autoComplete="tel" required/></label></div></section><section><h2>2. Szállítás</h2><div className="form-grid"><label><span>Név</span><input name="name" autoComplete="name" required/></label><label><span>Irányítószám</span><input name="postalCode" autoComplete="postal-code" required/></label><label><span>Város</span><input name="city" autoComplete="address-level2" required/></label><label><span>Cím</span><input name="line1" autoComplete="street-address" required/></label></div></section><label className="consent"><input type="checkbox" required/><span>Elolvastam és elfogadom az <Link to="/jogi/$slug" params={{slug:'aszf'}}>ÁSZF-et</Link>, valamint megismertem az <Link to="/jogi/$slug" params={{slug:'adatkezeles'}}>Adatkezelési tájékoztatót</Link>.</span></label><button className="btn btn-primary btn-block btn-large" disabled={busy}>{busy?'Rendelés létrehozása…':`Fizetési kötelezettséggel járó megrendelés · ${money(shop.total)}`}</button></form>
 <aside className="summary-card checkout-summary"><h2>Rendelésed</h2>{shop.cart.map(line=>{const p=shop.getProduct(line.productId);if(!p)return null;const label=getVariantLabel(p,line.variantId);return <div className="summary-product" key={`${p.id}:${line.variantId??'base'}`}><img src={getProductArt(p,line.variantId)} alt="" loading="lazy" decoding="async"/><span><b>{p.name}</b><small>{line.quantity} db{label?` · ${label}`:''}</small></span><strong>{money(getProductPrice(p,line.variantId)*line.quantity)}</strong></div>})}<div><span>Termékek</span><b>{money(shop.itemsSubtotal)}</b></div>{shop.discount>0&&<div><span>Kupon</span><b>− {money(shop.discount)}</b></div>}<div><span>Szállítás</span><b>{shop.shippingFee?money(shop.shippingFee):'Ingyenes'}</b></div><div className="summary-total"><span>Összesen</span><b>{money(shop.total)}</b></div><small>A megrendelés elküldése fizetési kötelezettséget keletkeztet.</small></aside></div></div>}
