import {Link,createFileRoute} from '@tanstack/react-router'
import {categories as demoCategories,products as demoProducts} from '../data/products'
import {getHomeData} from '../server/storefront'
import {ProductCard} from '../components/ProductCard'
import {RecentlyViewed} from '../components/RecentlyViewed'
export const Route=createFileRoute('/')({loader:()=>getHomeData(),component:Home})
function Home(){
 const data=Route.useLoaderData(),products=data?.products?.length?data.products:demoProducts,categories=data?.categories?.length?data.categories:demoCategories,hero=data?.sections?.find(s=>s.section_key==='hero')?.content??{},lead=products.find(p=>p.trending)??products[0]??demoProducts[0]
 const trending=products.filter(p=>p.trending).slice(0,4),fresh=products.filter(p=>p.newArrival).slice(0,4)
 return <>
 <section className="hero container-wide"><div className="hero-copy"><span className="pill">✨ {String(hero.eyebrow??'Friss trendek hetente')}</span><h1>Nem még egy játékwebshop.<br/><span>{String(hero.title??'Találd meg gyorsan azt, aminek örülni fog.')}</span></h1><p>{String(hero.description??'Trendi játékok, variánsok, okos ajánlatok és gyors vásárlási élmény — felesleges kattintgatás nélkül.')}</p><div className="hero-actions"><Link to="/termekek" search={{}} className="btn btn-primary btn-large">Felfedezem a játékokat →</Link><Link to="/ai-ajandekkereso" className="btn btn-ghost btn-large">✨ Segíts ajándékot választani</Link></div><div className="hero-trust"><span>✓ Mobilra optimalizált</span><span>✓ Biztonságos fizetés</span><span>✓ 14 napos elállási jog</span></div></div>
 <div className="hero-visual hero-visual-3d" aria-hidden="true"><div className="hero-orb orb-a"/><div className="hero-orb orb-b"/><div className="hero-orb orb-c"/><div className="hero-ring"/><div className="hero-platform"/><div className="hero-card hero-card-main"><img src={lead.art} alt=""/><div><span>Most pörög</span><b>{lead.name}</b></div></div><div className="hero-stack-card hero-stack-left"><span>🎟</span><div><b>Kuponmotor</b><small>Adminból időzíthető</small></div></div><div className="hero-stack-card hero-stack-right"><span>🎨</span><div><b>Variánsok</b><small>Szín · méret · eltérő ár</small></div></div><div className="hero-float top">🔥 Könnyű CSS 3D — nincs nehéz WebGL</div><div className="hero-float mid">🛍 Upsell + cross-sell</div><div className="hero-float bottom">⚡ Responsive + reduced-motion</div></div></section>
 <section className="container section"><div className="section-head"><div><span className="eyebrow">Böngéssz hangulat szerint</span><h2>Gyors út a jó választáshoz</h2></div><Link to="/termekek" search={{}}>Minden kategória →</Link></div><div className="category-grid">{categories.map(c=><Link key={c.name} to="/termekek" search={{category:c.name}} className="category-card"><span>{c.icon}</span><div><b>{c.name}</b><small>{c.blurb}</small></div><i>→</i></Link>)}</div></section>
 <section className="container section"><div className="section-head"><div><span className="eyebrow">Trend radar</span><h2>Amit most mindenki keres</h2></div></div><div className="product-grid">{(trending.length?trending:products.slice(0,4)).map(p=><ProductCard key={p.id} product={p}/>)}</div></section>
 <section className="feature-strip container"><div><span>🎁</span><b>Ajándék 60 mp alatt</b><p>Kor, keret és érdeklődés alapján.</p></div><div><span>🎨</span><b>Valódi variánsok</b><p>Szín, méret, SKU, ár és készlet.</p></div><div><span>🎟</span><b>Kupon + popup</b><p>Időzíthető marketingajánlatok.</p></div><div><span>🛒</span><b>Upsell / cross-sell</b><p>Adminból kapcsolható termékajánlók.</p></div></section>
 <section className="container section"><div className="section-head"><div><span className="eyebrow">Frissen érkezett</span><h2>Újdonságok</h2></div></div><div className="product-grid">{(fresh.length?fresh:products.slice(4,8)).map(p=><ProductCard key={p.id} product={p}/>)}</div></section><RecentlyViewed/>
 <section className="ai-banner container"><div><span className="pill">DINO MATCH ✨</span><h2>„Valami menő kell egy 7 éves dínórajongónak 8 000 Ft alatt.”</h2><p>Kor, keret és érdeklődés alapján céloz.</p><Link to="/ai-ajandekkereso" className="btn btn-light btn-large">Próbáld ki →</Link></div><div className="ai-orb"><span>🦕</span><span>🎁</span><span>✨</span></div></section>
 </>
}
