import {Link,createFileRoute} from '@tanstack/react-router'
import {categories as demoCategories,products as demoProducts} from '../data/products'
import {getHomeData} from '../server/storefront'
import {ProductCard} from '../components/ProductCard'
import {RecentlyViewed} from '../components/RecentlyViewed'
import {HeroShowcase} from '../components/HeroShowcase'
import {OrganizationJsonLd,SeoJsonLd,absoluteUrl} from '../lib/seo'
export const Route=createFileRoute('/')({loader:()=>getHomeData(),head:()=>({meta:[{title:'DinoToys.hu – játékok, ajándékötletek és trendtermékek'},{name:'description',content:'Fedezz fel trendi játékokat, variánsokat, ajándékötleteket és okos vásárlási funkciókat a DinoToys.hu webshopban.'}],links:[{rel:'canonical',href:absoluteUrl('/')}]}),component:Home})
function Home(){
 const data=Route.useLoaderData(),products=data?.products?.length?data.products:demoProducts,categories=data?.categories?.length?data.categories:demoCategories,hero=data?.sections?.find(s=>s.section_key==='hero')?.content??null
 const trending=products.filter(p=>p.trending).slice(0,4),fresh=products.filter(p=>p.newArrival).slice(0,4),featuredBarbie=products.find(p=>p.sourceSku==='JFP42'),starWarsProducts=products.filter(p=>p.brand==='Star Wars'),vader=starWarsProducts.find(p=>p.sourceSku==='G1277'),storm=starWarsProducts.find(p=>p.sourceSku==='G1279')
 return <>
 <OrganizationJsonLd/><SeoJsonLd data={{'@context':'https://schema.org','@type':'WebSite',name:'DinoToys.hu',url:absoluteUrl('/'),potentialAction:{'@type':'SearchAction',target:absoluteUrl('/termekek?q={search_term_string}'),'query-input':'required name=search_term_string'}}}/>
 <HeroShowcase products={products} liveContent={hero}/>
 {featuredBarbie&&<section className="barbie-launch container" aria-label="Barbie Deluxe Style újdonság"><div className="barbie-launch-copy"><span>ÚJDONSÁG · BARBIE DELUXE STYLE #7</span><h2>A stílusod ragyogjon.</h2><p>Jégkék metálfény, divatos részletek és három valódi termékfotó. Fedezd fel a Barbie Deluxe Style #7 babát.</p><div className="barbie-launch-actions"><Link to="/termek/$slug" params={{slug:featuredBarbie.slug}} className="btn btn-primary">Megnézem a terméket →</Link><b>{featuredBarbie.retailPrice.toLocaleString('hu-HU')} Ft</b></div></div><Link to="/termek/$slug" params={{slug:featuredBarbie.slug}} className="barbie-launch-image" aria-label={`${featuredBarbie.name} termékoldala`}><img src={featuredBarbie.art} alt={featuredBarbie.name} width="400" height="400" loading="eager"/></Link><i aria-hidden="true"/></section>}
 {starWarsProducts.length>0&&<section className="starwars-home container" aria-label="Star Wars kiemelt márka"><div className="starwars-home-stars" aria-hidden="true"/><div className="starwars-home-copy"><span>KIEMELT MÁRKAVILÁG · STAR WARS</span><h2>Válaszd ki<br/><em>az oldalad.</em></h2><p>Két 30 cm-es Titan Hero karakter, két eltérő hangulat. Darth Vader a sötét oldal erejével, Stormtrooper a Birodalom fegyelmével érkezik.</p><div className="starwars-home-actions"><Link to="/marka/star-wars" className="btn btn-light">Belépek a galaxisba →</Link><small>Hasbro · 4+ · Titan Hero Series</small></div></div><div className="starwars-home-duo">{vader&&<Link to="/termek/$slug" params={{slug:vader.slug}} className="starwars-home-product vader"><img src={vader.art} alt={vader.name}/><span>DARTH VADER</span><b>{vader.retailPrice.toLocaleString('hu-HU')} Ft</b></Link>}{storm&&<Link to="/termek/$slug" params={{slug:storm.slug}} className="starwars-home-product storm"><img src={storm.art} alt={storm.name}/><span>STORMTROOPER</span><b>{storm.retailPrice.toLocaleString('hu-HU')} Ft</b></Link>}</div></section>}
 <section className="container section"><div className="section-head"><div><span className="eyebrow">Böngéssz hangulat szerint</span><h2>Gyors út a jó választáshoz</h2></div><Link to="/termekek" search={{}}>Minden kategória →</Link></div><div className="category-grid">{categories.map(c=><Link key={c.name} to="/termekek" search={{category:c.name}} className="category-card"><span>{c.icon}</span><div><b>{c.name}</b><small>{c.blurb}</small></div><i>→</i></Link>)}</div></section>
 <section className="container section"><div className="section-head"><div><span className="eyebrow">Trend radar</span><h2>Amit most mindenki keres</h2></div></div><div className="product-grid">{(trending.length?trending:products.slice(0,4)).map(p=><ProductCard key={p.id} product={p}/>)}</div></section>
 <section className="feature-strip container"><div><span>🎁</span><b>Ajándék 60 mp alatt</b><p>Kor, keret és érdeklődés alapján.</p></div><div><span>🎨</span><b>Valódi variánsok</b><p>Szín, méret, SKU, ár és készlet.</p></div><div><span>🎟</span><b>Kupon + popup</b><p>Időzíthető marketingajánlatok.</p></div><div><span>🛒</span><b>Upsell / cross-sell</b><p>Adminból kapcsolható termékajánlók.</p></div></section>
 <section className="container section"><div className="section-head"><div><span className="eyebrow">Frissen érkezett</span><h2>Újdonságok</h2></div></div><div className="product-grid">{(fresh.length?fresh:products.slice(4,8)).map(p=><ProductCard key={p.id} product={p}/>)}</div></section><RecentlyViewed/>
 <section className="ai-banner container"><div><span className="pill">DINO MATCH ✨</span><h2>„Valami menő kell egy 7 éves dínórajongónak 8 000 Ft alatt.”</h2><p>Kor, keret és érdeklődés alapján céloz.</p><Link to="/ai-ajandekkereso" className="btn btn-light btn-large">Próbáld ki →</Link></div><div className="ai-orb"><span>🦕</span><span>🎁</span><span>✨</span></div></section>
 </>
}
