import {createFileRoute,Link} from '@tanstack/react-router'
import {useMemo,useState} from 'react'
import {products as demoProducts} from '../data/products'
import {ProductCard} from '../components/ProductCard'
import {money} from '../lib/format'
import {useShop} from '../lib/shop'
import {track} from '../lib/analytics'
import {getCartCrossSellProducts,getProductArt,getProductPrice,getVariantLabel} from '../lib/catalog'
export const Route=createFileRoute('/kosar')({component:Cart})
function Cart(){
 const shop=useShop(),[coupon,setCoupon]=useState(shop.appliedCouponCode??''),[message,setMessage]=useState<string|null>(null)
 const cross=useMemo(()=>getCartCrossSellProducts(shop.cart.map(l=>l.productId),demoProducts),[shop.cart])
 if(!shop.cart.length)return <div className="container section"><div className="empty-state large"><span>🛒</span><h1>A kosarad még üres</h1><Link to="/termekek" search={{}} className="btn btn-primary">Vásárlás</Link></div></div>
 return <div className="container section cart-page"><div className="page-title"><span className="eyebrow">Már majdnem kész</span><h1>Kosár</h1></div><div className="cart-layout"><div className="cart-lines"><div className="shipping-progress"><div><b>{shop.freeShippingLeft?`Még ${money(shop.freeShippingLeft)} az ingyenes szállításig`:'Megvan az ingyenes szállítás 🎉'}</b><span><i style={{width:`${Math.min(100,(shop.subtotal/shop.freeShippingThreshold)*100)}%`}}/></span></div></div>{shop.cart.map(line=>{const p=shop.getProduct(line.productId);if(!p)return null;const price=getProductPrice(p,line.variantId),label=getVariantLabel(p,line.variantId);return <div className="cart-line" key={`${p.id}:${line.variantId??'base'}`}><img src={getProductArt(p,line.variantId)}/><div className="cart-line-info"><Link to="/termek/$slug" params={{slug:p.slug}}><b>{p.name}</b></Link><small>{p.brand}{label?` · ${label}`:''}</small><button onClick={()=>shop.removeFromCart(p.id,line.variantId)}>Eltávolítás</button></div><div className="qty"><button onClick={()=>shop.updateQuantity(p.id,line.quantity-1,line.variantId)}>−</button><span>{line.quantity}</span><button onClick={()=>shop.updateQuantity(p.id,line.quantity+1,line.variantId)}>+</button></div><strong>{money(price*line.quantity)}</strong></div>})}
 {cross.length>0&&<section className="cart-cross-sell"><div className="section-head"><div><span className="eyebrow">Cross-sell</span><h2>Még jól jöhet mellé</h2></div></div><div className="product-grid compact-grid">{cross.map(p=><ProductCard key={p.id} product={p}/>)}</div></section>}</div>
 <aside className="summary-card"><h2>Összesítés</h2><div><span>Termékek</span><b>{money(shop.itemsSubtotal)}</b></div>{shop.discount>0&&<div><span>Kedvezmény ({shop.appliedCoupon?.code})</span><b>− {money(shop.discount)}</b></div>}<div><span>Szállítás</span><b>{shop.shippingFee?money(shop.shippingFee):'Ingyenes'}</b></div><div className="summary-total"><span>Fizetendő</span><b>{money(shop.total)}</b></div><div className="coupon-box"><b>Kuponkód</b><div className="coupon-row"><input value={coupon} onChange={e=>setCoupon(e.target.value.toUpperCase())} placeholder="WELCOME10"/><button className="btn btn-ghost" onClick={()=>{const r=shop.applyCoupon(coupon);setMessage(r.message)}}>Aktiválás</button></div>{shop.appliedCoupon&&<button className="coupon-remove" onClick={()=>{shop.removeCoupon();setMessage('Kupon eltávolítva.')}}>Kupon törlése</button>}{message&&<div className="coupon-message">{message}</div>}</div><Link to="/checkout" className="btn btn-primary btn-block" onClick={()=>track('begin_checkout',{value:shop.total,currency:'HUF',items:shop.cart.length})}>Tovább a pénztárhoz →</Link></aside></div></div>
}
