import {Link,createFileRoute,notFound} from '@tanstack/react-router'
import {useEffect,useMemo,useState} from 'react'
import {ProductCard} from '../components/ProductCard'
import {products} from '../data/products'
import {money} from '../lib/format'
import {useShop} from '../lib/shop'
import {trackCommerce} from '../lib/analytics'
import {getProductPage} from '../server/storefront'
import {findMatchingVariant,getAvailableOptionValues,getCrossSellProducts,getDefaultVariant,getProductArt,getProductCompareAtPrice,getProductDisplayPrice,getProductPrice,getProductStock,getUpsellProducts,getVariantLabel} from '../lib/catalog'
import {SeoJsonLd,absoluteUrl} from '../lib/seo'
export const Route=createFileRoute('/termek/$slug')({loader:async({params})=>{const live=await getProductPage({data:{slug:params.slug}});if(live)return live;const product=products.find(p=>p.slug===params.slug);if(!product)throw notFound();const related=products.filter(p=>p.id!==product.id&&(p.category===product.category||p.tags.some(t=>product.tags.includes(t)))).slice(0,4);return{product,related,upsell:getUpsellProducts(product),crossSell:getCrossSellProducts(product)}},head:({loaderData,params})=>{const p=loaderData?.product;const description=(p?.description||'').slice(0,155);const canonical=absoluteUrl('/termek/'+params.slug);return{meta:[{title:`${p?.name||'Termék'} | DinoToys.hu`},{name:'description',content:description},{property:'og:type',content:'product'},{property:'og:title',content:p?.name||'DinoToys.hu termék'},{property:'og:description',content:description},{property:'og:url',content:canonical},{property:'og:image',content:p?.art||absoluteUrl('/favicon.svg')},{name:'twitter:card',content:'summary_large_image'}],links:[{rel:'canonical',href:canonical}]}} ,component:ProductPage})
function ProductPage(){
 const {product,related,upsell,crossSell}=Route.useLoaderData(),shop=useShop(),[qty,setQty]=useState(1),initial=getDefaultVariant(product),[selection,setSelection]=useState<Record<string,string>>(initial?.attributes??{})
 useEffect(()=>{shop.markViewed(product.id,product);trackCommerce('view_item',product);setSelection(getDefaultVariant(product)?.attributes??{})},[product.id])
 const variant=useMemo(()=>findMatchingVariant(product,selection)??getDefaultVariant(product),[product,selection]),price=getProductPrice(product,variant?.id),compareAt=getProductCompareAtPrice(product,variant?.id),stock=getProductStock(product,variant?.id),saved=compareAt?compareAt-price:0,label=getVariantLabel(product,variant?.id)
 const activeVariants=product.variants?.filter(v=>v.active??true)??[];const prices=activeVariants.length?activeVariants.map(v=>v.retailPrice):[getProductDisplayPrice(product)];const productLd:any={'@context':'https://schema.org','@type':'Product',name:product.name,description:product.description,image:[product.art],sku:variant?.sku??product.sourceSku,brand:{'@type':'Brand',name:product.brand},category:product.category,offers:activeVariants.length?{'@type':'AggregateOffer',priceCurrency:'HUF',lowPrice:Math.min(...prices),highPrice:Math.max(...prices),offerCount:activeVariants.length,availability:getProductStock(product)>0?'https://schema.org/InStock':'https://schema.org/OutOfStock',url:absoluteUrl('/termek/'+product.slug)}:{'@type':'Offer',priceCurrency:'HUF',price:getProductDisplayPrice(product),availability:getProductStock(product)>0?'https://schema.org/InStock':'https://schema.org/OutOfStock',url:absoluteUrl('/termek/'+product.slug)}};if(/^\\d{13}$/.test(product.ean))productLd.gtin13=product.ean;const breadcrumbLd={'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Főoldal',item:absoluteUrl('/')},{'@type':'ListItem',position:2,name:product.category,item:absoluteUrl('/termekek')},{'@type':'ListItem',position:3,name:product.name,item:absoluteUrl('/termek/'+product.slug)}]};
 return <><SeoJsonLd data={productLd}/><SeoJsonLd data={breadcrumbLd}/><div className="container section"><div className="breadcrumbs"><Link to="/">Főoldal</Link><span>/</span><Link to="/termekek" search={{category:product.category}}>{product.category}</Link><span>/</span><b>{product.name}</b></div><div className="product-detail"><div className="gallery"><div className="gallery-main"><img src={getProductArt(product,variant?.id)} alt={product.name}/>{product.trending&&<span className="gallery-badge">🔥 Trend</span>}</div></div><div className="detail-info"><p className="product-meta">{product.brand} · SKU: {variant?.sku??product.sourceSku}</p><h1>{product.name}</h1><div className="rating detail-rating"><span>★ {product.rating}</span><a href="#reviews">{product.reviewCount} értékelés</a></div><div className="detail-price"><strong>{money(price)}</strong>{compareAt&&<del>{money(compareAt)}</del>}{saved>0&&compareAt&&<span>-{Math.round(saved/compareAt*100)}%</span>}</div><div className="availability-card"><span className="availability-dot"/><div><b>{stock>0?'Raktáron':'Elfogyott'}</b><small>{label||'Alapváltozat'}</small></div><strong>{stock} db</strong></div><p className="detail-description">{product.description}</p><ul className="highlight-list">{product.highlights.map(h=><li key={h}>✓ {h}</li>)}</ul>
 {product.options?.length?<div className="variant-panel"><div className="variant-panel-head"><b>Válassz változatot</b><small>{label}</small></div>{product.options.map(option=><div className="variant-group" key={option.name}><span>{option.label}</span><div className="variant-values">{getAvailableOptionValues(product,option.name,selection).map(value=><button key={value.value} disabled={!value.available} className={`${selection[option.name]===value.value?'selected':''} ${option.display==='swatch'?'swatch-btn':''}`} onClick={()=>setSelection(current=>({...current,[option.name]:value.value}))}>{option.display==='swatch'&&<i style={{background:value.swatch??'#ddd'}}/>}<b>{value.label}</b></button>)}</div></div>)}</div>:null}
 <div className="buy-box"><div className="qty"><button onClick={()=>setQty(Math.max(1,qty-1))}>−</button><span>{qty}</span><button onClick={()=>setQty(Math.min(Math.max(1,stock),qty+1))}>+</button></div><button className="btn btn-primary btn-buy" disabled={stock<=0} onClick={()=>{shop.addToCart(product.id,qty,product,variant?.id);trackCommerce('add_to_cart',product,qty)}}>Kosárba · {money(price*qty)}</button></div><div className="secondary-actions"><button onClick={()=>shop.toggleWishlist(product.id,product)}>{shop.wishlist.includes(product.id)?'♥ Mentve':'♡ Kedvencekhez'}</button><button onClick={()=>shop.toggleCompare(product.id,product)}>⇄ Összehasonlítás</button></div></div></div>
 <section className="detail-panels"><div><span className="eyebrow">Termékadatok</span><h2>Amit érdemes tudni</h2><dl><div><dt>Márka</dt><dd>{product.brand}</dd></div><div><dt>Kor</dt><dd>{product.ageFrom}+ év</dd></div><div><dt>EAN</dt><dd>{variant?.ean??product.ean}</dd></div><div><dt>Variáns</dt><dd>{label||'Nincs'}</dd></div></dl></div><div className="safety-card"><div className="safety-heading"><span>🛡️</span><div><b>Biztonsági információk</b><small>Online vásárlás előtt látható</small></div></div><p>{product.compliance.warning}</p></div></section>
 {upsell.length>0&&<section className="section"><div className="section-head"><div><span className="eyebrow">Upsell</span><h2>Prémiumabb alternatívák</h2></div></div><div className="product-grid">{upsell.map(p=><ProductCard key={p.id} product={p}/>)}</div></section>}
 {crossSell.length>0&&<section className="section"><div className="section-head"><div><span className="eyebrow">Cross-sell</span><h2>Ezt még gyakran együtt választják</h2></div></div><div className="product-grid">{crossSell.map(p=><ProductCard key={p.id} product={p}/>)}</div></section>}
 {related.length>0&&<section className="section"><div className="section-head"><div><span className="eyebrow">Kapcsolódó</span><h2>Ehhez még passzolhat</h2></div></div><div className="product-grid">{related.map(p=><ProductCard key={p.id} product={p}/>)}</div></section>}</div></>
}
