import {useEffect,useMemo,useState} from 'react'
import {adminApi} from '../../lib/admin-api'
import {demoIntegrationDefaults,integrationProviders,readDemoIntegrationConfig,resetDemoIntegrationConfig,writeDemoIntegrationConfig,type DemoIntegrationConfig,type IntegrationProvider,type IntegrationSection} from '../../lib/integration-config'
import {money} from '../../lib/format'

type Health={provider:string;kind:string;ready:boolean;requiredSecrets:string[];configuredSecrets:string[]}
type Props={demo:boolean;simpleMode:boolean;onMessage:(message:string|null)=>void}

const sections:Array<{id:IntegrationSection;label:string;hint:string;icon:string}>=[
 {id:'overview',label:'Áttekintés',hint:'Mi van bekötve?',icon:'◫'},
 {id:'shipping',label:'Szállítás',hint:'GLS · FOXPOST · Packeta',icon:'🚚'},
 {id:'billing',label:'Számlázás',hint:'Számlázz.hu · Billingo',icon:'🧾'},
 {id:'payment',label:'Fizetés',hint:'Barion · Stripe',icon:'💳'},
 {id:'seo',label:'SEO & mérés',hint:'GA4 · GTM · Search Console',icon:'🔎'},
 {id:'email',label:'E-mail',hint:'Resend',icon:'✉️'},
 {id:'supplier',label:'Beszállító',hint:'DinoToys adatkapcsolat',icon:'🦕'},
]

export function IntegrationsWorkspace({demo,simpleMode,onMessage}:Props){
 const [section,setSection]=useState<IntegrationSection>('overview')
 const [config,setConfig]=useState<DemoIntegrationConfig>(demoIntegrationDefaults)
 const [health,setHealth]=useState<Health[]>([])
 const [saved,setSaved]=useState(false)
 useEffect(()=>{setConfig(readDemoIntegrationConfig())},[])
 useEffect(()=>{if(demo)return;adminApi<Health[]>('/api/v1/admin/integrations/health').then(setHealth).catch(error=>onMessage(error.message))},[demo])
 const save=()=>{writeDemoIntegrationConfig(config);setSaved(true);window.setTimeout(()=>setSaved(false),1600)}
 const reset=()=>{resetDemoIntegrationConfig();setConfig(demoIntegrationDefaults);setSaved(true);window.setTimeout(()=>setSaved(false),1600)}
 const providers=useMemo(()=>integrationProviders.filter(provider=>section==='overview'||provider.section===section),[section])
 const healthFor=(provider:IntegrationProvider)=>health.find(item=>item.provider===provider.id||item.provider===provider.shortName.toLowerCase())
 const readyCount=integrationProviders.filter(provider=>{const h=healthFor(provider);if(h)return h.ready;if(provider.id==='ga4')return Boolean(config.seo.ga4MeasurementId);if(provider.id==='gtm')return Boolean(config.seo.gtmContainerId);if(provider.id==='search-console')return Boolean(config.seo.searchConsoleVerification);if(provider.id==='resend')return config.email.resend.enabled;return false}).length
 return <>
  <div className="admin2-heading row integration-heading"><div><span className="eyebrow">Webshop összekötések</span><h1>Integrációk</h1><p>Innen állíthatod be a szállítást, számlázást, fizetést, SEO-mérést, e-mailt és beszállítói kapcsolatokat. Demóban titkos API-kulcsot nem kérünk és nem tárolunk.</p></div><div className="integration-heading-actions"><span className="integration-save-state">{saved?'✓ Elmentve a böngészőben':demo?'Demó beállítások':'Éles állapot'}</span><button className="btn btn-ghost" onClick={reset}>Demó alaphelyzet</button><button className="btn btn-primary" onClick={save}>Beállítások mentése</button></div></div>
  <div className="integration-summary"><div><span>Előkészített kapcsolatok</span><b>{integrationProviders.length}</b><small>egy helyről kezelhető</small></div><div><span>Most konfigurált</span><b>{readyCount}</b><small>azonosító vagy szerverkulcs alapján</small></div><div><span>Mód</span><b>{demo?'DEMÓ':'ÉLES'}</b><small>{demo?'nincs külső API-hívás':'szerveres ellenőrzés'}</small></div><div><span>Adatvédelem</span><b>Consent</b><small>mérés csak engedéllyel</small></div></div>
  <nav className="integration-tabs">{sections.map(item=><button key={item.id} className={section===item.id?'active':''} onClick={()=>setSection(item.id)}><i>{item.icon}</i><span><b>{item.label}</b><small>{item.hint}</small></span></button>)}</nav>
  {section==='overview'&&<IntegrationOverview config={config} providers={providers} health={health} onOpen={setSection}/>} 
  {section==='shipping'&&<ShippingPanel config={config} setConfig={setConfig} providers={providers} health={health} simpleMode={simpleMode}/>} 
  {section==='billing'&&<BillingPanel config={config} setConfig={setConfig} providers={providers} health={health} simpleMode={simpleMode}/>} 
  {section==='payment'&&<PaymentPanel config={config} setConfig={setConfig} providers={providers} health={health} simpleMode={simpleMode}/>} 
  {section==='seo'&&<SeoPanel config={config} setConfig={setConfig} providers={providers} health={health} simpleMode={simpleMode}/>} 
  {section==='email'&&<EmailPanel config={config} setConfig={setConfig} providers={providers} health={health} simpleMode={simpleMode}/>} 
  {section==='supplier'&&<SupplierPanel config={config} setConfig={setConfig} providers={providers} health={health} simpleMode={simpleMode}/>} 
 </>
}

function IntegrationOverview({config,providers,health,onOpen}:{config:DemoIntegrationConfig;providers:IntegrationProvider[];health:Health[];onOpen:(id:IntegrationSection)=>void}){
 const rows:Array<{id:IntegrationSection;title:string;value:string;detail:string;state:'ok'|'warn'}>=[
  {id:'shipping',title:'Szállítás',value:[config.shipping.gls.enabled&&'GLS',config.shipping.foxpost.enabled&&'FOXPOST',config.shipping.packeta.enabled&&'Packeta'].filter(Boolean).join(' · ')||'Nincs bekapcsolva',detail:'Checkout szállítási módok és későbbi címkekezelés',state:(config.shipping.gls.enabled||config.shipping.foxpost.enabled||config.shipping.packeta.enabled)?'ok':'warn'},
  {id:'billing',title:'Számlázás',value:config.billing.provider==='szamlazz'?'Számlázz.hu':config.billing.provider==='billingo'?'Billingo':'Nincs kiválasztva',detail:'Automatikus számlázó a rendelési folyamat után',state:config.billing.provider==='none'?'warn':'ok'},
  {id:'payment',title:'Fizetés',value:config.payment.barion.enabled?'Barion':config.payment.stripe.enabled?'Stripe':'Még csak demo fizetés',detail:'Élesítéskor szerveroldali fizetésindítás és callback kell',state:(config.payment.barion.enabled||config.payment.stripe.enabled)?'ok':'warn'},
  {id:'seo',title:'SEO & mérés',value:config.seo.gtmContainerId||config.seo.ga4MeasurementId||'Azonosító még nincs',detail:'GA4 / GTM / Search Console és e-commerce események',state:(config.seo.gtmContainerId||config.seo.ga4MeasurementId)?'ok':'warn'},
  {id:'email',title:'E-mail',value:config.email.resend.enabled?'Resend bekapcsolva':'Nincs bekapcsolva',detail:'Rendelés-visszaigazolás és tranzakciós levelek',state:config.email.resend.enabled?'ok':'warn'},
 ]
 return <><section className="integration-roadmap"><div><span className="eyebrow">Javasolt sorrend</span><h2>Így építjük fel az éles webshopot</h2><p>Most az admin és a checkout elő van készítve. Az API-kulcsok később kizárólag szerveroldalon kerülnek be.</p></div><ol><li><b>1</b><span>Szállítás<small>GLS + FOXPOST + Packeta</small></span></li><li><b>2</b><span>Számlázás<small>Számlázz.hu vagy Billingo</small></span></li><li><b>3</b><span>Fizetés<small>Barion / Stripe sandbox, majd éles</small></span></li><li><b>4</b><span>SEO & mérés<small>GA4 + GTM + Search Console</small></span></li><li><b>5</b><span>E-mail<small>Resend tranzakciós levelek</small></span></li></ol></section>
 <div className="integration-overview-grid">{rows.map(row=><button key={row.id} onClick={()=>onOpen(row.id)} className="integration-overview-card"><span className={`integration-status ${row.state}`}>{row.state==='ok'?'✓':'!'}</span><div><small>{row.title}</small><b>{row.value}</b><p>{row.detail}</p></div><i>→</i></button>)}</div>
 <section className="integration-provider-matrix"><div className="admin2-card-head"><div><span className="eyebrow">Provider térkép</span><h2>Előkészített szolgáltatók</h2></div><span>{providers.length} kapcsolat</span></div><div className="integration-provider-mini-grid">{providers.map(provider=>{const item=health.find(x=>x.provider===provider.id);return <div key={provider.id}><span>{provider.icon}</span><div><b>{provider.shortName}</b><small>{provider.description}</small></div><strong className={item?.ready?'ready':''}>{item?.ready?'KÉSZ':'ELŐKÉSZÍTVE'}</strong></div>})}</div></section></>
}

function ShippingPanel({config,setConfig,providers,health,simpleMode}:{config:DemoIntegrationConfig;setConfig:React.Dispatch<React.SetStateAction<DemoIntegrationConfig>>;providers:IntegrationProvider[];health:Health[];simpleMode:boolean}){
 const change=(provider:'packeta'|'foxpost'|'gls',patch:Partial<DemoIntegrationConfig['shipping']['packeta']>)=>setConfig(current=>({...current,shipping:{...current.shipping,[provider]:{...current.shipping[provider],...patch}}}))
 return <><PanelIntro title="Szállítási integrációk" text="A vásárló ezeket a módokat látja a pénztárban. A demó már szolgáltatónként külön kezeli a díjakat; élesben innen indul majd a csomagfeladás, címke és tracking."/><div className="integration-provider-grid">{providers.map(provider=>{const key=provider.id as 'packeta'|'foxpost'|'gls',state=config.shipping[key],h=health.find(x=>x.provider===provider.id);return <ProviderCard key={provider.id} provider={provider} health={h} simpleMode={simpleMode}><Switch label="Megjelenjen a pénztárban" checked={state.enabled} onChange={checked=>change(key,{enabled:checked})}/><NumberSetting label="Szállítási díj" value={state.feeHuf} suffix="Ft" onChange={value=>change(key,{feeHuf:value})}/><NumberSetting label="Ingyenes ettől a kosárértéktől" value={state.freeAboveHuf} suffix="Ft" onChange={value=>change(key,{freeAboveHuf:value})}/></ProviderCard>})}</div><section className="integration-info-strip"><b>Mi működik már?</b><span>A checkout automatikusan a bekapcsolt GLS / FOXPOST / Packeta módokat és a hozzájuk megadott díjakat használja.</span><b>Mi kell az éleshez?</b><span>Szerveroldali API-hitelesítés, csomagpont widget/feed, csomaglétrehozás, címke, tracking és webhook/státuszszinkron.</span></section></>
}

function BillingPanel({config,setConfig,providers,health,simpleMode}:{config:DemoIntegrationConfig;setConfig:React.Dispatch<React.SetStateAction<DemoIntegrationConfig>>;providers:IntegrationProvider[];health:Health[];simpleMode:boolean}){
 const setBilling=(patch:Partial<DemoIntegrationConfig['billing']>)=>setConfig(current=>({...current,billing:{...current.billing,...patch}}))
 return <><PanelIntro title="Számlázási integrációk" text="Válaszd ki, melyik rendszer készítse majd automatikusan a számlát. Egyszerre egy elsődleges számlázót használunk."/><div className="integration-provider-grid">{providers.map(provider=><ProviderCard key={provider.id} provider={provider} health={health.find(x=>x.provider===provider.id)} simpleMode={simpleMode}><label className="integration-radio"><input type="radio" name="billing-provider" checked={config.billing.provider===provider.id} onChange={()=>setBilling({provider:provider.id as 'szamlazz'|'billingo'})}/><span><b>Legyen ez az elsődleges számlázó</b><small>{config.billing.provider===provider.id?'Kiválasztva':'Nincs kiválasztva'}</small></span></label></ProviderCard>)}</div><section className="integration-settings-card"><h3>Automatikus számlázási szabály</h3><div className="integration-form-grid"><Switch label="Automatikus számlakészítés" checked={config.billing.autoIssue} onChange={value=>setBilling({autoIssue:value})}/><Switch label="E-számla" checked={config.billing.eInvoice} onChange={value=>setBilling({eInvoice:value})}/><Switch label="A számlázó küldje ki e-mailben" checked={config.billing.sendEmail} onChange={value=>setBilling({sendEmail:value})}/><label><span>Mikor készüljön?</span><select value={config.billing.issueWhen} onChange={e=>setBilling({issueWhen:e.target.value as 'paid'|'processing'})}><option value="paid">Sikeres fizetés után</option><option value="processing">Feldolgozás megkezdésekor</option></select></label><label><span>Számla előtag</span><input value={config.billing.invoicePrefix} onChange={e=>setBilling({invoicePrefix:e.target.value.toUpperCase().slice(0,12)})} placeholder="DT"/></label></div></section></>
}

function PaymentPanel({config,setConfig,providers,health,simpleMode}:{config:DemoIntegrationConfig;setConfig:React.Dispatch<React.SetStateAction<DemoIntegrationConfig>>;providers:IntegrationProvider[];health:Health[];simpleMode:boolean}){
 return <><PanelIntro title="Online fizetés" text="A valódi bankkártyás fizetés szerveroldali integráció. Most az admin konfigurációját és a sandbox felkészítést építjük be."/><div className="integration-provider-grid">{providers.map(provider=><ProviderCard key={provider.id} provider={provider} health={health.find(x=>x.provider===provider.id)} simpleMode={simpleMode}>{provider.id==='barion'?<><Switch label="Barion engedélyezése" checked={config.payment.barion.enabled} onChange={enabled=>setConfig(current=>({...current,payment:{...current.payment,barion:{...current.payment.barion,enabled}}}))}/><Switch label="Sandbox / teszt mód" checked={config.payment.barion.sandbox} onChange={sandbox=>setConfig(current=>({...current,payment:{...current.payment,barion:{...current.payment.barion,sandbox}}}))}/></>:<Switch label="Stripe engedélyezése" checked={config.payment.stripe.enabled} onChange={enabled=>setConfig(current=>({...current,payment:{...current.payment,stripe:{enabled}}}))}/>}</ProviderCard>)}</div><section className="integration-info-strip"><b>Biztonsági szabály</b><span>Bankkártyaadatot a DinoToys szervere nem tárol. A fizetés a választott szolgáltató biztonságos folyamatán keresztül történik.</span></section></>
}

function SeoPanel({config,setConfig,providers,health,simpleMode}:{config:DemoIntegrationConfig;setConfig:React.Dispatch<React.SetStateAction<DemoIntegrationConfig>>;providers:IntegrationProvider[];health:Health[];simpleMode:boolean}){
 const setSeo=(patch:Partial<DemoIntegrationConfig['seo']>)=>setConfig(current=>({...current,seo:{...current.seo,...patch}}))
 return <><PanelIntro title="SEO, Analytics és mérés" text="A technikai SEO már az oldal része. Itt kötjük hozzá a Google és marketing mérőrendszereket úgy, hogy a hozzájárulási beállításokat is tiszteletben tartsuk."/><div className="seo-readiness"><div><span>✓</span><b>Canonical URL-ek</b><small>beépítve</small></div><div><span>✓</span><b>Product structured data</b><small>beépítve</small></div><div><span>✓</span><b>Robots + sitemap</b><small>projektben előkészítve</small></div><div><span>✓</span><b>E-commerce dataLayer</b><small>termék · kosár · checkout</small></div></div><div className="integration-provider-grid">{providers.map(provider=><ProviderCard key={provider.id} provider={provider} health={health.find(x=>x.provider===provider.id)} simpleMode={simpleMode}>{provider.id==='ga4'&&<><TextSetting label="GA4 Measurement ID" value={config.seo.ga4MeasurementId} placeholder="G-XXXXXXXXXX" onChange={ga4MeasurementId=>setSeo({ga4MeasurementId})}/><Switch label="E-commerce események" checked={config.seo.ecommerceEvents} onChange={ecommerceEvents=>setSeo({ecommerceEvents})}/></>}{provider.id==='gtm'&&<TextSetting label="GTM Container ID" value={config.seo.gtmContainerId} placeholder="GTM-XXXXXXX" onChange={gtmContainerId=>setSeo({gtmContainerId})}/>} {provider.id==='search-console'&&<TextSetting label="Google site verification token" value={config.seo.searchConsoleVerification} placeholder="verification token" onChange={searchConsoleVerification=>setSeo({searchConsoleVerification})}/>}</ProviderCard>)}</div><section className="integration-settings-card"><h3>Marketing mérés</h3><div className="integration-form-grid"><TextSetting label="Meta Pixel ID (opcionális)" value={config.seo.metaPixelId} placeholder="123456789…" onChange={metaPixelId=>setSeo({metaPixelId})}/></div><p className="admin2-help">A GA4/GTM demó konfigurációt a storefront runtime már fel tudja használni. Éles Search Console API-hozzáféréshez OAuth2 kapcsolat kell; a verification token önmagában csak a tulajdon igazolásához használható.</p></section></>
}

function EmailPanel({config,setConfig,providers,health,simpleMode}:{config:DemoIntegrationConfig;setConfig:React.Dispatch<React.SetStateAction<DemoIntegrationConfig>>;providers:IntegrationProvider[];health:Health[];simpleMode:boolean}){
 const update=(patch:Partial<DemoIntegrationConfig['email']['resend']>)=>setConfig(current=>({...current,email:{resend:{...current.email.resend,...patch}}}))
 return <><PanelIntro title="E-mail integráció" text="A rendelés-visszaigazolás, számlaértesítés és státuszlevelek innen kapják majd a feladó adatait."/><div className="integration-provider-grid single">{providers.map(provider=><ProviderCard key={provider.id} provider={provider} health={health.find(x=>x.provider===provider.id)} simpleMode={simpleMode}><Switch label="Resend használata" checked={config.email.resend.enabled} onChange={enabled=>update({enabled})}/><TextSetting label="Feladó neve" value={config.email.resend.fromName} placeholder="DinoToys.hu" onChange={fromName=>update({fromName})}/><TextSetting label="Feladó e-mail" value={config.email.resend.fromEmail} placeholder="rendeles@dinotoys.hu" onChange={fromEmail=>update({fromEmail})}/><TextSetting label="Válaszcím" value={config.email.resend.replyTo} placeholder="ugyfelszolgalat@dinotoys.hu" onChange={replyTo=>update({replyTo})}/></ProviderCard>)}</div></>
}

function SupplierPanel({config,setConfig,providers,health,simpleMode}:{config:DemoIntegrationConfig;setConfig:React.Dispatch<React.SetStateAction<DemoIntegrationConfig>>;providers:IntegrationProvider[];health:Health[];simpleMode:boolean}){
 const update=(patch:Partial<DemoIntegrationConfig['supplier']['dinotoys']>)=>setConfig(current=>({...current,supplier:{dinotoys:{...current.supplier.dinotoys,...patch}}}))
 return <><PanelIntro title="Beszállítói kapcsolatok" text="Itt készítjük elő az automatikus termék-, ár-, készlet- és képfrissítést. A saját készlet és a beszállítói készlet továbbra is külön adat marad."/><div className="integration-provider-grid single">{providers.map(provider=><ProviderCard key={provider.id} provider={provider} health={health.find(x=>x.provider===provider.id)} simpleMode={simpleMode}><Switch label="DinoToys adatkapcsolat engedélyezése" checked={config.supplier.dinotoys.enabled} onChange={enabled=>update({enabled})}/><label className="integration-setting"><span><b>Frissítés gyakorisága</b><small>Demó beállítás, automatikus futtatás még nincs.</small></span><select value={config.supplier.dinotoys.syncMode} onChange={e=>update({syncMode:e.target.value as 'manual'|'daily'|'hourly'})}><option value="manual">Kézzel</option><option value="daily">Naponta</option><option value="hourly">Óránként</option></select></label></ProviderCard>)}</div></>
}

function PanelIntro({title,text}:{title:string;text:string}){return <div className="integration-panel-intro"><span className="eyebrow">Integrációs modul</span><h2>{title}</h2><p>{text}</p></div>}

function ProviderCard({provider,health,simpleMode,children}:{provider:IntegrationProvider;health?:Health;simpleMode:boolean;children?:React.ReactNode}){
 const ready=health?.ready
 return <article className="integration-provider-card"><div className="integration-provider-head"><span>{provider.icon}</span><div><small>{provider.recommended?'AJÁNLOTT':'INTEGRÁCIÓ'}</small><h3>{provider.name}</h3><p>{provider.description}</p></div><strong className={ready?'ready':''}>{ready?'KÉSZ':health?'KULCS KELL':'DEMÓ'}</strong></div><div className="integration-capabilities">{provider.capabilities.map(item=><span key={item}>✓ {item}</span>)}</div>{children&&<div className="integration-card-settings">{children}</div>}<footer><a href={provider.docsUrl} target="_blank" rel="noreferrer">Dokumentáció ↗</a>{!simpleMode&&provider.secretNames.length>0&&<code>{provider.secretNames.join(' · ')}</code>}</footer></article>
}

function Switch({label,checked,onChange}:{label:string;checked:boolean;onChange:(value:boolean)=>void}){return <label className="integration-setting switch"><span><b>{label}</b><small>{checked?'Bekapcsolva':'Kikapcsolva'}</small></span><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/></label>}
function NumberSetting({label,value,suffix,onChange}:{label:string;value:number;suffix:string;onChange:(value:number)=>void}){return <label className="integration-setting"><span><b>{label}</b><small>{money(value)}</small></span><div className="integration-number"><input type="number" min="0" step="10" value={value} onChange={e=>onChange(Math.max(0,Number(e.target.value)))}/><i>{suffix}</i></div></label>}
function TextSetting({label,value,placeholder,onChange}:{label:string;value:string;placeholder:string;onChange:(value:string)=>void}){return <label className="integration-setting text"><span><b>{label}</b><small>{value?'Megadva':'Még nincs megadva'}</small></span><input value={value} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/></label>}
