import {Link} from '@tanstack/react-router'
import type{Product} from '../data/products'
import {money} from '../lib/format'
import {useShop} from '../lib/shop'
import {trackCommerce} from '../lib/analytics'
import {getDefaultVariant,getProductDisplayCompareAtPrice,getProductDisplayPrice,getProductStock} from '../lib/catalog'
export function ProductCard({product}:{product:Product}){
 const shop=useShop(),liked=shop.wishlist.includes(product.id),compared=shop.compare.includes(product.id),variant=getDefaultVariant(product),price=getProductDisplayPrice(product),compareAt=getProductDisplayCompareAtPrice(product),stock=getProductStock(product),validPrice=Number.isFinite(price)&&price>0,imageSrc=variant?.art??product.art??'/favicon.svg'
 return <article className="product-card"><div className="product-media"><Link to="/termek/$slug" params={{slug:product.slug}}><img src={imageSrc} alt={product.name} loading="lazy" decoding="async" onError={e=>{if(!e.currentTarget.src.endsWith('/favicon.svg'))e.currentTarget.src='/favicon.svg'}}/></Link><div className="badges">{product.newArrival&&<span className="badge">ÚJ</span>}{product.trending&&<span className="badge badge-dark">TREND</span>}{product.variants?.length&&<span className="badge badge-soft">{product.variants.length} variáns</span>}</div><button className={`heart ${liked?'selected':''}`} onClick={()=>{shop.toggleWishlist(product.id,product);trackCommerce('add_to_wishlist',product)}}>{liked?'♥':'♡'}</button></div><div className="product-body"><p className="product-meta">{product.brand} · {product.category}</p><Link to="/termek/$slug" params={{slug:product.slug}} className="product-title">{product.name}</Link>{product.reviewCount>0&&<div className="rating"><span>★ {product.rating}</span><small>({product.reviewCount})</small></div>}<div className="price-row"><strong>{validPrice?(product.variants?.length?`-tól ${money(price)}`:money(price)):'Ár hamarosan'}</strong>{validPrice&&compareAt&&compareAt>price&&<del>{money(compareAt)}</del>}</div><div className="stock-line"><i className={stock>10?'in-stock':'low-stock'}></i>{stock>10?'Raktáron':stock>0?`Már csak ${stock} db`:'Jelenleg nem rendelhető'}</div><div className="card-actions"><button className="btn btn-primary" disabled={stock<=0||!validPrice} onClick={()=>{if(!validPrice)return;shop.addToCart(product.id,1,product,variant?.id);trackCommerce('add_to_cart',product)}}>{validPrice?'Kosárba':'Nem rendelhető'}</button><button className={`btn btn-icon ${compared?'active':''}`} onClick={()=>shop.toggleCompare(product.id,product)}>⇄</button></div></div></article>
}
