/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AiAjandekkeresoRouteImport } from './routes/ai-ajandekkereso'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as KapcsolatRouteImport } from './routes/kapcsolat'
import { Route as KedvencekRouteImport } from './routes/kedvencek'
import { Route as KosarRouteImport } from './routes/kosar'
import { Route as OsszehasonlitasRouteImport } from './routes/osszehasonlitas'
import { Route as SzallitasRouteImport } from './routes/szallitas'
import { Route as TermekekRouteImport } from './routes/termekek'
import { Route as VisszakuldesRouteImport } from './routes/visszakuldes'
import { Route as JogiSlugRouteImport } from './routes/jogi.$slug'
import { Route as TermekSlugRouteImport } from './routes/termek.$slug'
import { Route as ApiV1CheckoutRouteImport } from './routes/api.v1.checkout'
import { Route as ApiV1HealthRouteImport } from './routes/api.v1.health'
import { Route as ApiV1ProductsRouteImport } from './routes/api.v1.products'
import { Route as ApiV1AdminAuditRouteImport } from './routes/api.v1.admin.audit'
import { Route as ApiV1AdminBootstrapRouteImport } from './routes/api.v1.admin.bootstrap'
import { Route as ApiV1AdminHeroRouteImport } from './routes/api.v1.admin.hero'
import { Route as ApiV1AdminMeRouteImport } from './routes/api.v1.admin.me'
import { Route as ApiV1AdminMediaRouteImport } from './routes/api.v1.admin.media'
import { Route as ApiV1AdminOrdersRouteImport } from './routes/api.v1.admin.orders'
import { Route as ApiV1AdminProductsRouteImport } from './routes/api.v1.admin.products'
import { Route as ApiV1AdminRolesRouteImport } from './routes/api.v1.admin.roles'
import { Route as ApiV1AdminUsersRouteImport } from './routes/api.v1.admin.users'
import { Route as ApiV1ProductsSlugRouteImport } from './routes/api.v1.products.$slug'
import { Route as ApiV1AdminIntegrationsHealthRouteImport } from './routes/api.v1.admin.integrations.health'
import { Route as ApiV1AdminMediaIdRouteImport } from './routes/api.v1.admin.media.$id'
import { Route as ApiV1AdminOrdersIdRouteImport } from './routes/api.v1.admin.orders.$id'
import { Route as ApiV1AdminProductsIdRouteImport } from './routes/api.v1.admin.products.$id'
import { Route as ApiV1AdminProductsImportBarbieRouteImport } from './routes/api.v1.admin.products.import-barbie'
import { Route as ApiV1AdminResourcesResourceRouteImport } from './routes/api.v1.admin.resources.$resource'
import { Route as ApiV1AdminUsersIdRouteImport } from './routes/api.v1.admin.users.$id'
import { Route as ApiV1AdminProductsIdCategoriesRouteImport } from './routes/api.v1.admin.products.$id.categories'
import { Route as ApiV1AdminProductsIdImagesRouteImport } from './routes/api.v1.admin.products.$id.images'
import { Route as ApiV1AdminProductsIdInventoryRouteImport } from './routes/api.v1.admin.products.$id.inventory'
import { Route as ApiV1AdminProductsIdVariantsRouteImport } from './routes/api.v1.admin.products.$id.variants'
import { Route as ApiV1AdminResourcesResourceIdRouteImport } from './routes/api.v1.admin.resources.$resource.$id'
import { Route as ApiV1AdminRolesIdPermissionsRouteImport } from './routes/api.v1.admin.roles.$id.permissions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAjandekkeresoRoute = AiAjandekkeresoRouteImport.update({
  id: '/ai-ajandekkereso',
  path: '/ai-ajandekkereso',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const KapcsolatRoute = KapcsolatRouteImport.update({
  id: '/kapcsolat',
  path: '/kapcsolat',
  getParentRoute: () => rootRouteImport,
} as any)
const KedvencekRoute = KedvencekRouteImport.update({
  id: '/kedvencek',
  path: '/kedvencek',
  getParentRoute: () => rootRouteImport,
} as any)
const KosarRoute = KosarRouteImport.update({
  id: '/kosar',
  path: '/kosar',
  getParentRoute: () => rootRouteImport,
} as any)
const OsszehasonlitasRoute = OsszehasonlitasRouteImport.update({
  id: '/osszehasonlitas',
  path: '/osszehasonlitas',
  getParentRoute: () => rootRouteImport,
} as any)
const SzallitasRoute = SzallitasRouteImport.update({
  id: '/szallitas',
  path: '/szallitas',
  getParentRoute: () => rootRouteImport,
} as any)
const TermekekRoute = TermekekRouteImport.update({
  id: '/termekek',
  path: '/termekek',
  getParentRoute: () => rootRouteImport,
} as any)
const VisszakuldesRoute = VisszakuldesRouteImport.update({
  id: '/visszakuldes',
  path: '/visszakuldes',
  getParentRoute: () => rootRouteImport,
} as any)
const JogiSlugRoute = JogiSlugRouteImport.update({
  id: '/jogi/$slug',
  path: '/jogi/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TermekSlugRoute = TermekSlugRouteImport.update({
  id: '/termek/$slug',
  path: '/termek/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CheckoutRoute = ApiV1CheckoutRouteImport.update({
  id: '/api/v1/checkout',
  path: '/api/v1/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1HealthRoute = ApiV1HealthRouteImport.update({
  id: '/api/v1/health',
  path: '/api/v1/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ProductsRoute = ApiV1ProductsRouteImport.update({
  id: '/api/v1/products',
  path: '/api/v1/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AdminAuditRoute = ApiV1AdminAuditRouteImport.update({
  id: '/api/v1/admin/audit',
  path: '/api/v1/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AdminBootstrapRoute = ApiV1AdminBootstrapRouteImport.update({
  id: '/api/v1/admin/bootstrap',
  path: '/api/v1/admin/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AdminHeroRoute = ApiV1AdminHeroRouteImport.update({
  id: '/api/v1/admin/hero',
  path: '/api/v1/admin/hero',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AdminMeRoute = ApiV1AdminMeRouteImport.update({
  id: '/api/v1/admin/me',
  path: '/api/v1/admin/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AdminMediaRoute = ApiV1AdminMediaRouteImport.update({
  id: '/api/v1/admin/media',
  path: '/api/v1/admin/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AdminOrdersRoute = ApiV1AdminOrdersRouteImport.update({
  id: '/api/v1/admin/orders',
  path: '/api/v1/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AdminProductsRoute = ApiV1AdminProductsRouteImport.update({
  id: '/api/v1/admin/products',
  path: '/api/v1/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AdminRolesRoute = ApiV1AdminRolesRouteImport.update({
  id: '/api/v1/admin/roles',
  path: '/api/v1/admin/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AdminUsersRoute = ApiV1AdminUsersRouteImport.update({
  id: '/api/v1/admin/users',
  path: '/api/v1/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ProductsSlugRoute = ApiV1ProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiV1ProductsRoute,
} as any)
const ApiV1AdminIntegrationsHealthRoute =
  ApiV1AdminIntegrationsHealthRouteImport.update({
    id: '/api/v1/admin/integrations/health',
    path: '/api/v1/admin/integrations/health',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1AdminMediaIdRoute = ApiV1AdminMediaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV1AdminMediaRoute,
} as any)
const ApiV1AdminOrdersIdRoute = ApiV1AdminOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV1AdminOrdersRoute,
} as any)
const ApiV1AdminProductsIdRoute = ApiV1AdminProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV1AdminProductsRoute,
} as any)
const ApiV1AdminProductsImportBarbieRoute =
  ApiV1AdminProductsImportBarbieRouteImport.update({
    id: '/import-barbie',
    path: '/import-barbie',
    getParentRoute: () => ApiV1AdminProductsRoute,
  } as any)
const ApiV1AdminResourcesResourceRoute =
  ApiV1AdminResourcesResourceRouteImport.update({
    id: '/api/v1/admin/resources/$resource',
    path: '/api/v1/admin/resources/$resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1AdminUsersIdRoute = ApiV1AdminUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV1AdminUsersRoute,
} as any)
const ApiV1AdminProductsIdCategoriesRoute =
  ApiV1AdminProductsIdCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => ApiV1AdminProductsIdRoute,
  } as any)
const ApiV1AdminProductsIdImagesRoute =
  ApiV1AdminProductsIdImagesRouteImport.update({
    id: '/images',
    path: '/images',
    getParentRoute: () => ApiV1AdminProductsIdRoute,
  } as any)
const ApiV1AdminProductsIdInventoryRoute =
  ApiV1AdminProductsIdInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => ApiV1AdminProductsIdRoute,
  } as any)
const ApiV1AdminProductsIdVariantsRoute =
  ApiV1AdminProductsIdVariantsRouteImport.update({
    id: '/variants',
    path: '/variants',
    getParentRoute: () => ApiV1AdminProductsIdRoute,
  } as any)
const ApiV1AdminResourcesResourceIdRoute =
  ApiV1AdminResourcesResourceIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ApiV1AdminResourcesResourceRoute,
  } as any)
const ApiV1AdminRolesIdPermissionsRoute =
  ApiV1AdminRolesIdPermissionsRouteImport.update({
    id: '/$id/permissions',
    path: '/$id/permissions',
    getParentRoute: () => ApiV1AdminRolesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-ajandekkereso': typeof AiAjandekkeresoRoute
  '/checkout': typeof CheckoutRoute
  '/kapcsolat': typeof KapcsolatRoute
  '/kedvencek': typeof KedvencekRoute
  '/kosar': typeof KosarRoute
  '/osszehasonlitas': typeof OsszehasonlitasRoute
  '/szallitas': typeof SzallitasRoute
  '/termekek': typeof TermekekRoute
  '/visszakuldes': typeof VisszakuldesRoute
  '/jogi/$slug': typeof JogiSlugRoute
  '/termek/$slug': typeof TermekSlugRoute
  '/api/v1/checkout': typeof ApiV1CheckoutRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/products': typeof ApiV1ProductsRouteWithChildren
  '/api/v1/admin/audit': typeof ApiV1AdminAuditRoute
  '/api/v1/admin/bootstrap': typeof ApiV1AdminBootstrapRoute
  '/api/v1/admin/hero': typeof ApiV1AdminHeroRoute
  '/api/v1/admin/me': typeof ApiV1AdminMeRoute
  '/api/v1/admin/media': typeof ApiV1AdminMediaRouteWithChildren
  '/api/v1/admin/orders': typeof ApiV1AdminOrdersRouteWithChildren
  '/api/v1/admin/products': typeof ApiV1AdminProductsRouteWithChildren
  '/api/v1/admin/roles': typeof ApiV1AdminRolesRouteWithChildren
  '/api/v1/admin/users': typeof ApiV1AdminUsersRouteWithChildren
  '/api/v1/products/$slug': typeof ApiV1ProductsSlugRoute
  '/api/v1/admin/integrations/health': typeof ApiV1AdminIntegrationsHealthRoute
  '/api/v1/admin/media/$id': typeof ApiV1AdminMediaIdRoute
  '/api/v1/admin/orders/$id': typeof ApiV1AdminOrdersIdRoute
  '/api/v1/admin/products/$id': typeof ApiV1AdminProductsIdRouteWithChildren
  '/api/v1/admin/products/import-barbie': typeof ApiV1AdminProductsImportBarbieRoute
  '/api/v1/admin/resources/$resource': typeof ApiV1AdminResourcesResourceRouteWithChildren
  '/api/v1/admin/users/$id': typeof ApiV1AdminUsersIdRoute
  '/api/v1/admin/products/$id/categories': typeof ApiV1AdminProductsIdCategoriesRoute
  '/api/v1/admin/products/$id/images': typeof ApiV1AdminProductsIdImagesRoute
  '/api/v1/admin/products/$id/inventory': typeof ApiV1AdminProductsIdInventoryRoute
  '/api/v1/admin/products/$id/variants': typeof ApiV1AdminProductsIdVariantsRoute
  '/api/v1/admin/resources/$resource/$id': typeof ApiV1AdminResourcesResourceIdRoute
  '/api/v1/admin/roles/$id/permissions': typeof ApiV1AdminRolesIdPermissionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-ajandekkereso': typeof AiAjandekkeresoRoute
  '/checkout': typeof CheckoutRoute
  '/kapcsolat': typeof KapcsolatRoute
  '/kedvencek': typeof KedvencekRoute
  '/kosar': typeof KosarRoute
  '/osszehasonlitas': typeof OsszehasonlitasRoute
  '/szallitas': typeof SzallitasRoute
  '/termekek': typeof TermekekRoute
  '/visszakuldes': typeof VisszakuldesRoute
  '/jogi/$slug': typeof JogiSlugRoute
  '/termek/$slug': typeof TermekSlugRoute
  '/api/v1/checkout': typeof ApiV1CheckoutRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/products': typeof ApiV1ProductsRouteWithChildren
  '/api/v1/admin/audit': typeof ApiV1AdminAuditRoute
  '/api/v1/admin/bootstrap': typeof ApiV1AdminBootstrapRoute
  '/api/v1/admin/hero': typeof ApiV1AdminHeroRoute
  '/api/v1/admin/me': typeof ApiV1AdminMeRoute
  '/api/v1/admin/media': typeof ApiV1AdminMediaRouteWithChildren
  '/api/v1/admin/orders': typeof ApiV1AdminOrdersRouteWithChildren
  '/api/v1/admin/products': typeof ApiV1AdminProductsRouteWithChildren
  '/api/v1/admin/roles': typeof ApiV1AdminRolesRouteWithChildren
  '/api/v1/admin/users': typeof ApiV1AdminUsersRouteWithChildren
  '/api/v1/products/$slug': typeof ApiV1ProductsSlugRoute
  '/api/v1/admin/integrations/health': typeof ApiV1AdminIntegrationsHealthRoute
  '/api/v1/admin/media/$id': typeof ApiV1AdminMediaIdRoute
  '/api/v1/admin/orders/$id': typeof ApiV1AdminOrdersIdRoute
  '/api/v1/admin/products/$id': typeof ApiV1AdminProductsIdRouteWithChildren
  '/api/v1/admin/products/import-barbie': typeof ApiV1AdminProductsImportBarbieRoute
  '/api/v1/admin/resources/$resource': typeof ApiV1AdminResourcesResourceRouteWithChildren
  '/api/v1/admin/users/$id': typeof ApiV1AdminUsersIdRoute
  '/api/v1/admin/products/$id/categories': typeof ApiV1AdminProductsIdCategoriesRoute
  '/api/v1/admin/products/$id/images': typeof ApiV1AdminProductsIdImagesRoute
  '/api/v1/admin/products/$id/inventory': typeof ApiV1AdminProductsIdInventoryRoute
  '/api/v1/admin/products/$id/variants': typeof ApiV1AdminProductsIdVariantsRoute
  '/api/v1/admin/resources/$resource/$id': typeof ApiV1AdminResourcesResourceIdRoute
  '/api/v1/admin/roles/$id/permissions': typeof ApiV1AdminRolesIdPermissionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-ajandekkereso': typeof AiAjandekkeresoRoute
  '/checkout': typeof CheckoutRoute
  '/kapcsolat': typeof KapcsolatRoute
  '/kedvencek': typeof KedvencekRoute
  '/kosar': typeof KosarRoute
  '/osszehasonlitas': typeof OsszehasonlitasRoute
  '/szallitas': typeof SzallitasRoute
  '/termekek': typeof TermekekRoute
  '/visszakuldes': typeof VisszakuldesRoute
  '/jogi/$slug': typeof JogiSlugRoute
  '/termek/$slug': typeof TermekSlugRoute
  '/api/v1/checkout': typeof ApiV1CheckoutRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/products': typeof ApiV1ProductsRouteWithChildren
  '/api/v1/admin/audit': typeof ApiV1AdminAuditRoute
  '/api/v1/admin/bootstrap': typeof ApiV1AdminBootstrapRoute
  '/api/v1/admin/hero': typeof ApiV1AdminHeroRoute
  '/api/v1/admin/me': typeof ApiV1AdminMeRoute
  '/api/v1/admin/media': typeof ApiV1AdminMediaRouteWithChildren
  '/api/v1/admin/orders': typeof ApiV1AdminOrdersRouteWithChildren
  '/api/v1/admin/products': typeof ApiV1AdminProductsRouteWithChildren
  '/api/v1/admin/roles': typeof ApiV1AdminRolesRouteWithChildren
  '/api/v1/admin/users': typeof ApiV1AdminUsersRouteWithChildren
  '/api/v1/products/$slug': typeof ApiV1ProductsSlugRoute
  '/api/v1/admin/integrations/health': typeof ApiV1AdminIntegrationsHealthRoute
  '/api/v1/admin/media/$id': typeof ApiV1AdminMediaIdRoute
  '/api/v1/admin/orders/$id': typeof ApiV1AdminOrdersIdRoute
  '/api/v1/admin/products/$id': typeof ApiV1AdminProductsIdRouteWithChildren
  '/api/v1/admin/products/import-barbie': typeof ApiV1AdminProductsImportBarbieRoute
  '/api/v1/admin/resources/$resource': typeof ApiV1AdminResourcesResourceRouteWithChildren
  '/api/v1/admin/users/$id': typeof ApiV1AdminUsersIdRoute
  '/api/v1/admin/products/$id/categories': typeof ApiV1AdminProductsIdCategoriesRoute
  '/api/v1/admin/products/$id/images': typeof ApiV1AdminProductsIdImagesRoute
  '/api/v1/admin/products/$id/inventory': typeof ApiV1AdminProductsIdInventoryRoute
  '/api/v1/admin/products/$id/variants': typeof ApiV1AdminProductsIdVariantsRoute
  '/api/v1/admin/resources/$resource/$id': typeof ApiV1AdminResourcesResourceIdRoute
  '/api/v1/admin/roles/$id/permissions': typeof ApiV1AdminRolesIdPermissionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ai-ajandekkereso'
    | '/checkout'
    | '/kapcsolat'
    | '/kedvencek'
    | '/kosar'
    | '/osszehasonlitas'
    | '/szallitas'
    | '/termekek'
    | '/visszakuldes'
    | '/jogi/$slug'
    | '/termek/$slug'
    | '/api/v1/checkout'
    | '/api/v1/health'
    | '/api/v1/products'
    | '/api/v1/admin/audit'
    | '/api/v1/admin/bootstrap'
    | '/api/v1/admin/hero'
    | '/api/v1/admin/me'
    | '/api/v1/admin/media'
    | '/api/v1/admin/orders'
    | '/api/v1/admin/products'
    | '/api/v1/admin/roles'
    | '/api/v1/admin/users'
    | '/api/v1/products/$slug'
    | '/api/v1/admin/integrations/health'
    | '/api/v1/admin/media/$id'
    | '/api/v1/admin/orders/$id'
    | '/api/v1/admin/products/$id'
    | '/api/v1/admin/products/import-barbie'
    | '/api/v1/admin/resources/$resource'
    | '/api/v1/admin/users/$id'
    | '/api/v1/admin/products/$id/categories'
    | '/api/v1/admin/products/$id/images'
    | '/api/v1/admin/products/$id/inventory'
    | '/api/v1/admin/products/$id/variants'
    | '/api/v1/admin/resources/$resource/$id'
    | '/api/v1/admin/roles/$id/permissions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ai-ajandekkereso'
    | '/checkout'
    | '/kapcsolat'
    | '/kedvencek'
    | '/kosar'
    | '/osszehasonlitas'
    | '/szallitas'
    | '/termekek'
    | '/visszakuldes'
    | '/jogi/$slug'
    | '/termek/$slug'
    | '/api/v1/checkout'
    | '/api/v1/health'
    | '/api/v1/products'
    | '/api/v1/admin/audit'
    | '/api/v1/admin/bootstrap'
    | '/api/v1/admin/hero'
    | '/api/v1/admin/me'
    | '/api/v1/admin/media'
    | '/api/v1/admin/orders'
    | '/api/v1/admin/products'
    | '/api/v1/admin/roles'
    | '/api/v1/admin/users'
    | '/api/v1/products/$slug'
    | '/api/v1/admin/integrations/health'
    | '/api/v1/admin/media/$id'
    | '/api/v1/admin/orders/$id'
    | '/api/v1/admin/products/$id'
    | '/api/v1/admin/products/import-barbie'
    | '/api/v1/admin/resources/$resource'
    | '/api/v1/admin/users/$id'
    | '/api/v1/admin/products/$id/categories'
    | '/api/v1/admin/products/$id/images'
    | '/api/v1/admin/products/$id/inventory'
    | '/api/v1/admin/products/$id/variants'
    | '/api/v1/admin/resources/$resource/$id'
    | '/api/v1/admin/roles/$id/permissions'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ai-ajandekkereso'
    | '/checkout'
    | '/kapcsolat'
    | '/kedvencek'
    | '/kosar'
    | '/osszehasonlitas'
    | '/szallitas'
    | '/termekek'
    | '/visszakuldes'
    | '/jogi/$slug'
    | '/termek/$slug'
    | '/api/v1/checkout'
    | '/api/v1/health'
    | '/api/v1/products'
    | '/api/v1/admin/audit'
    | '/api/v1/admin/bootstrap'
    | '/api/v1/admin/hero'
    | '/api/v1/admin/me'
    | '/api/v1/admin/media'
    | '/api/v1/admin/orders'
    | '/api/v1/admin/products'
    | '/api/v1/admin/roles'
    | '/api/v1/admin/users'
    | '/api/v1/products/$slug'
    | '/api/v1/admin/integrations/health'
    | '/api/v1/admin/media/$id'
    | '/api/v1/admin/orders/$id'
    | '/api/v1/admin/products/$id'
    | '/api/v1/admin/products/import-barbie'
    | '/api/v1/admin/resources/$resource'
    | '/api/v1/admin/users/$id'
    | '/api/v1/admin/products/$id/categories'
    | '/api/v1/admin/products/$id/images'
    | '/api/v1/admin/products/$id/inventory'
    | '/api/v1/admin/products/$id/variants'
    | '/api/v1/admin/resources/$resource/$id'
    | '/api/v1/admin/roles/$id/permissions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AiAjandekkeresoRoute: typeof AiAjandekkeresoRoute
  CheckoutRoute: typeof CheckoutRoute
  KapcsolatRoute: typeof KapcsolatRoute
  KedvencekRoute: typeof KedvencekRoute
  KosarRoute: typeof KosarRoute
  OsszehasonlitasRoute: typeof OsszehasonlitasRoute
  SzallitasRoute: typeof SzallitasRoute
  TermekekRoute: typeof TermekekRoute
  VisszakuldesRoute: typeof VisszakuldesRoute
  JogiSlugRoute: typeof JogiSlugRoute
  TermekSlugRoute: typeof TermekSlugRoute
  ApiV1CheckoutRoute: typeof ApiV1CheckoutRoute
  ApiV1HealthRoute: typeof ApiV1HealthRoute
  ApiV1ProductsRoute: typeof ApiV1ProductsRouteWithChildren
  ApiV1AdminAuditRoute: typeof ApiV1AdminAuditRoute
  ApiV1AdminBootstrapRoute: typeof ApiV1AdminBootstrapRoute
  ApiV1AdminHeroRoute: typeof ApiV1AdminHeroRoute
  ApiV1AdminMeRoute: typeof ApiV1AdminMeRoute
  ApiV1AdminMediaRoute: typeof ApiV1AdminMediaRouteWithChildren
  ApiV1AdminOrdersRoute: typeof ApiV1AdminOrdersRouteWithChildren
  ApiV1AdminProductsRoute: typeof ApiV1AdminProductsRouteWithChildren
  ApiV1AdminRolesRoute: typeof ApiV1AdminRolesRouteWithChildren
  ApiV1AdminUsersRoute: typeof ApiV1AdminUsersRouteWithChildren
  ApiV1AdminIntegrationsHealthRoute: typeof ApiV1AdminIntegrationsHealthRoute
  ApiV1AdminResourcesResourceRoute: typeof ApiV1AdminResourcesResourceRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-ajandekkereso': {
      id: '/ai-ajandekkereso'
      path: '/ai-ajandekkereso'
      fullPath: '/ai-ajandekkereso'
      preLoaderRoute: typeof AiAjandekkeresoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kapcsolat': {
      id: '/kapcsolat'
      path: '/kapcsolat'
      fullPath: '/kapcsolat'
      preLoaderRoute: typeof KapcsolatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kedvencek': {
      id: '/kedvencek'
      path: '/kedvencek'
      fullPath: '/kedvencek'
      preLoaderRoute: typeof KedvencekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kosar': {
      id: '/kosar'
      path: '/kosar'
      fullPath: '/kosar'
      preLoaderRoute: typeof KosarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/osszehasonlitas': {
      id: '/osszehasonlitas'
      path: '/osszehasonlitas'
      fullPath: '/osszehasonlitas'
      preLoaderRoute: typeof OsszehasonlitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/szallitas': {
      id: '/szallitas'
      path: '/szallitas'
      fullPath: '/szallitas'
      preLoaderRoute: typeof SzallitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termekek': {
      id: '/termekek'
      path: '/termekek'
      fullPath: '/termekek'
      preLoaderRoute: typeof TermekekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visszakuldes': {
      id: '/visszakuldes'
      path: '/visszakuldes'
      fullPath: '/visszakuldes'
      preLoaderRoute: typeof VisszakuldesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogi/$slug': {
      id: '/jogi/$slug'
      path: '/jogi/$slug'
      fullPath: '/jogi/$slug'
      preLoaderRoute: typeof JogiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termek/$slug': {
      id: '/termek/$slug'
      path: '/termek/$slug'
      fullPath: '/termek/$slug'
      preLoaderRoute: typeof TermekSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/checkout': {
      id: '/api/v1/checkout'
      path: '/api/v1/checkout'
      fullPath: '/api/v1/checkout'
      preLoaderRoute: typeof ApiV1CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/health': {
      id: '/api/v1/health'
      path: '/api/v1/health'
      fullPath: '/api/v1/health'
      preLoaderRoute: typeof ApiV1HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/products': {
      id: '/api/v1/products'
      path: '/api/v1/products'
      fullPath: '/api/v1/products'
      preLoaderRoute: typeof ApiV1ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/admin/audit': {
      id: '/api/v1/admin/audit'
      path: '/api/v1/admin/audit'
      fullPath: '/api/v1/admin/audit'
      preLoaderRoute: typeof ApiV1AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/admin/bootstrap': {
      id: '/api/v1/admin/bootstrap'
      path: '/api/v1/admin/bootstrap'
      fullPath: '/api/v1/admin/bootstrap'
      preLoaderRoute: typeof ApiV1AdminBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/admin/hero': {
      id: '/api/v1/admin/hero'
      path: '/api/v1/admin/hero'
      fullPath: '/api/v1/admin/hero'
      preLoaderRoute: typeof ApiV1AdminHeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/admin/me': {
      id: '/api/v1/admin/me'
      path: '/api/v1/admin/me'
      fullPath: '/api/v1/admin/me'
      preLoaderRoute: typeof ApiV1AdminMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/admin/media': {
      id: '/api/v1/admin/media'
      path: '/api/v1/admin/media'
      fullPath: '/api/v1/admin/media'
      preLoaderRoute: typeof ApiV1AdminMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/admin/orders': {
      id: '/api/v1/admin/orders'
      path: '/api/v1/admin/orders'
      fullPath: '/api/v1/admin/orders'
      preLoaderRoute: typeof ApiV1AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/admin/products': {
      id: '/api/v1/admin/products'
      path: '/api/v1/admin/products'
      fullPath: '/api/v1/admin/products'
      preLoaderRoute: typeof ApiV1AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/admin/roles': {
      id: '/api/v1/admin/roles'
      path: '/api/v1/admin/roles'
      fullPath: '/api/v1/admin/roles'
      preLoaderRoute: typeof ApiV1AdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/admin/users': {
      id: '/api/v1/admin/users'
      path: '/api/v1/admin/users'
      fullPath: '/api/v1/admin/users'
      preLoaderRoute: typeof ApiV1AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/products/$slug': {
      id: '/api/v1/products/$slug'
      path: '/$slug'
      fullPath: '/api/v1/products/$slug'
      preLoaderRoute: typeof ApiV1ProductsSlugRouteImport
      parentRoute: typeof ApiV1ProductsRoute
    }
    '/api/v1/admin/integrations/health': {
      id: '/api/v1/admin/integrations/health'
      path: '/api/v1/admin/integrations/health'
      fullPath: '/api/v1/admin/integrations/health'
      preLoaderRoute: typeof ApiV1AdminIntegrationsHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/admin/media/$id': {
      id: '/api/v1/admin/media/$id'
      path: '/$id'
      fullPath: '/api/v1/admin/media/$id'
      preLoaderRoute: typeof ApiV1AdminMediaIdRouteImport
      parentRoute: typeof ApiV1AdminMediaRoute
    }
    '/api/v1/admin/orders/$id': {
      id: '/api/v1/admin/orders/$id'
      path: '/$id'
      fullPath: '/api/v1/admin/orders/$id'
      preLoaderRoute: typeof ApiV1AdminOrdersIdRouteImport
      parentRoute: typeof ApiV1AdminOrdersRoute
    }
    '/api/v1/admin/products/$id': {
      id: '/api/v1/admin/products/$id'
      path: '/$id'
      fullPath: '/api/v1/admin/products/$id'
      preLoaderRoute: typeof ApiV1AdminProductsIdRouteImport
      parentRoute: typeof ApiV1AdminProductsRoute
    }
    '/api/v1/admin/products/import-barbie': {
      id: '/api/v1/admin/products/import-barbie'
      path: '/import-barbie'
      fullPath: '/api/v1/admin/products/import-barbie'
      preLoaderRoute: typeof ApiV1AdminProductsImportBarbieRouteImport
      parentRoute: typeof ApiV1AdminProductsRoute
    }
    '/api/v1/admin/resources/$resource': {
      id: '/api/v1/admin/resources/$resource'
      path: '/api/v1/admin/resources/$resource'
      fullPath: '/api/v1/admin/resources/$resource'
      preLoaderRoute: typeof ApiV1AdminResourcesResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/admin/users/$id': {
      id: '/api/v1/admin/users/$id'
      path: '/$id'
      fullPath: '/api/v1/admin/users/$id'
      preLoaderRoute: typeof ApiV1AdminUsersIdRouteImport
      parentRoute: typeof ApiV1AdminUsersRoute
    }
    '/api/v1/admin/products/$id/categories': {
      id: '/api/v1/admin/products/$id/categories'
      path: '/categories'
      fullPath: '/api/v1/admin/products/$id/categories'
      preLoaderRoute: typeof ApiV1AdminProductsIdCategoriesRouteImport
      parentRoute: typeof ApiV1AdminProductsIdRoute
    }
    '/api/v1/admin/products/$id/images': {
      id: '/api/v1/admin/products/$id/images'
      path: '/images'
      fullPath: '/api/v1/admin/products/$id/images'
      preLoaderRoute: typeof ApiV1AdminProductsIdImagesRouteImport
      parentRoute: typeof ApiV1AdminProductsIdRoute
    }
    '/api/v1/admin/products/$id/inventory': {
      id: '/api/v1/admin/products/$id/inventory'
      path: '/inventory'
      fullPath: '/api/v1/admin/products/$id/inventory'
      preLoaderRoute: typeof ApiV1AdminProductsIdInventoryRouteImport
      parentRoute: typeof ApiV1AdminProductsIdRoute
    }
    '/api/v1/admin/products/$id/variants': {
      id: '/api/v1/admin/products/$id/variants'
      path: '/variants'
      fullPath: '/api/v1/admin/products/$id/variants'
      preLoaderRoute: typeof ApiV1AdminProductsIdVariantsRouteImport
      parentRoute: typeof ApiV1AdminProductsIdRoute
    }
    '/api/v1/admin/resources/$resource/$id': {
      id: '/api/v1/admin/resources/$resource/$id'
      path: '/$id'
      fullPath: '/api/v1/admin/resources/$resource/$id'
      preLoaderRoute: typeof ApiV1AdminResourcesResourceIdRouteImport
      parentRoute: typeof ApiV1AdminResourcesResourceRoute
    }
    '/api/v1/admin/roles/$id/permissions': {
      id: '/api/v1/admin/roles/$id/permissions'
      path: '/$id/permissions'
      fullPath: '/api/v1/admin/roles/$id/permissions'
      preLoaderRoute: typeof ApiV1AdminRolesIdPermissionsRouteImport
      parentRoute: typeof ApiV1AdminRolesRoute
    }
  }
}

interface ApiV1ProductsRouteChildren {
  ApiV1ProductsSlugRoute: typeof ApiV1ProductsSlugRoute
}

const ApiV1ProductsRouteChildren: ApiV1ProductsRouteChildren = {
  ApiV1ProductsSlugRoute: ApiV1ProductsSlugRoute,
}

const ApiV1ProductsRouteWithChildren = ApiV1ProductsRoute._addFileChildren(
  ApiV1ProductsRouteChildren,
)

interface ApiV1AdminMediaRouteChildren {
  ApiV1AdminMediaIdRoute: typeof ApiV1AdminMediaIdRoute
}

const ApiV1AdminMediaRouteChildren: ApiV1AdminMediaRouteChildren = {
  ApiV1AdminMediaIdRoute: ApiV1AdminMediaIdRoute,
}

const ApiV1AdminMediaRouteWithChildren = ApiV1AdminMediaRoute._addFileChildren(
  ApiV1AdminMediaRouteChildren,
)

interface ApiV1AdminOrdersRouteChildren {
  ApiV1AdminOrdersIdRoute: typeof ApiV1AdminOrdersIdRoute
}

const ApiV1AdminOrdersRouteChildren: ApiV1AdminOrdersRouteChildren = {
  ApiV1AdminOrdersIdRoute: ApiV1AdminOrdersIdRoute,
}

const ApiV1AdminOrdersRouteWithChildren =
  ApiV1AdminOrdersRoute._addFileChildren(ApiV1AdminOrdersRouteChildren)

interface ApiV1AdminProductsIdRouteChildren {
  ApiV1AdminProductsIdCategoriesRoute: typeof ApiV1AdminProductsIdCategoriesRoute
  ApiV1AdminProductsIdImagesRoute: typeof ApiV1AdminProductsIdImagesRoute
  ApiV1AdminProductsIdInventoryRoute: typeof ApiV1AdminProductsIdInventoryRoute
  ApiV1AdminProductsIdVariantsRoute: typeof ApiV1AdminProductsIdVariantsRoute
}

const ApiV1AdminProductsIdRouteChildren: ApiV1AdminProductsIdRouteChildren = {
  ApiV1AdminProductsIdCategoriesRoute: ApiV1AdminProductsIdCategoriesRoute,
  ApiV1AdminProductsIdImagesRoute: ApiV1AdminProductsIdImagesRoute,
  ApiV1AdminProductsIdInventoryRoute: ApiV1AdminProductsIdInventoryRoute,
  ApiV1AdminProductsIdVariantsRoute: ApiV1AdminProductsIdVariantsRoute,
}

const ApiV1AdminProductsIdRouteWithChildren =
  ApiV1AdminProductsIdRoute._addFileChildren(ApiV1AdminProductsIdRouteChildren)

interface ApiV1AdminProductsRouteChildren {
  ApiV1AdminProductsIdRoute: typeof ApiV1AdminProductsIdRouteWithChildren
  ApiV1AdminProductsImportBarbieRoute: typeof ApiV1AdminProductsImportBarbieRoute
}

const ApiV1AdminProductsRouteChildren: ApiV1AdminProductsRouteChildren = {
  ApiV1AdminProductsIdRoute: ApiV1AdminProductsIdRouteWithChildren,
  ApiV1AdminProductsImportBarbieRoute: ApiV1AdminProductsImportBarbieRoute,
}

const ApiV1AdminProductsRouteWithChildren =
  ApiV1AdminProductsRoute._addFileChildren(ApiV1AdminProductsRouteChildren)

interface ApiV1AdminRolesRouteChildren {
  ApiV1AdminRolesIdPermissionsRoute: typeof ApiV1AdminRolesIdPermissionsRoute
}

const ApiV1AdminRolesRouteChildren: ApiV1AdminRolesRouteChildren = {
  ApiV1AdminRolesIdPermissionsRoute: ApiV1AdminRolesIdPermissionsRoute,
}

const ApiV1AdminRolesRouteWithChildren = ApiV1AdminRolesRoute._addFileChildren(
  ApiV1AdminRolesRouteChildren,
)

interface ApiV1AdminUsersRouteChildren {
  ApiV1AdminUsersIdRoute: typeof ApiV1AdminUsersIdRoute
}

const ApiV1AdminUsersRouteChildren: ApiV1AdminUsersRouteChildren = {
  ApiV1AdminUsersIdRoute: ApiV1AdminUsersIdRoute,
}

const ApiV1AdminUsersRouteWithChildren = ApiV1AdminUsersRoute._addFileChildren(
  ApiV1AdminUsersRouteChildren,
)

interface ApiV1AdminResourcesResourceRouteChildren {
  ApiV1AdminResourcesResourceIdRoute: typeof ApiV1AdminResourcesResourceIdRoute
}

const ApiV1AdminResourcesResourceRouteChildren: ApiV1AdminResourcesResourceRouteChildren =
  {
    ApiV1AdminResourcesResourceIdRoute: ApiV1AdminResourcesResourceIdRoute,
  }

const ApiV1AdminResourcesResourceRouteWithChildren =
  ApiV1AdminResourcesResourceRoute._addFileChildren(
    ApiV1AdminResourcesResourceRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AiAjandekkeresoRoute: AiAjandekkeresoRoute,
  CheckoutRoute: CheckoutRoute,
  KapcsolatRoute: KapcsolatRoute,
  KedvencekRoute: KedvencekRoute,
  KosarRoute: KosarRoute,
  OsszehasonlitasRoute: OsszehasonlitasRoute,
  SzallitasRoute: SzallitasRoute,
  TermekekRoute: TermekekRoute,
  VisszakuldesRoute: VisszakuldesRoute,
  JogiSlugRoute: JogiSlugRoute,
  TermekSlugRoute: TermekSlugRoute,
  ApiV1CheckoutRoute: ApiV1CheckoutRoute,
  ApiV1HealthRoute: ApiV1HealthRoute,
  ApiV1ProductsRoute: ApiV1ProductsRouteWithChildren,
  ApiV1AdminAuditRoute: ApiV1AdminAuditRoute,
  ApiV1AdminBootstrapRoute: ApiV1AdminBootstrapRoute,
  ApiV1AdminHeroRoute: ApiV1AdminHeroRoute,
  ApiV1AdminMeRoute: ApiV1AdminMeRoute,
  ApiV1AdminMediaRoute: ApiV1AdminMediaRouteWithChildren,
  ApiV1AdminOrdersRoute: ApiV1AdminOrdersRouteWithChildren,
  ApiV1AdminProductsRoute: ApiV1AdminProductsRouteWithChildren,
  ApiV1AdminRolesRoute: ApiV1AdminRolesRouteWithChildren,
  ApiV1AdminUsersRoute: ApiV1AdminUsersRouteWithChildren,
  ApiV1AdminIntegrationsHealthRoute: ApiV1AdminIntegrationsHealthRoute,
  ApiV1AdminResourcesResourceRoute:
    ApiV1AdminResourcesResourceRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
